Apsolventski staz
etf-sarajevo/zamger pull request #40
Opened 2020-02-09 20:07 UTC by aladinkapic

2020-02-09 20:10 UTC, aladinkapic commented
U apsoventski.md imaju naznačene izmjene, do kojih je došlo u kojim fajlovima i čitava logika izmjena

2020-02-23 10:47 UTC, vljubovic requested changes

2020-02-23 10:47 UTC, vljubovic commented on student/intro.php
> +            $s_s = (int)db_fetch_row(db_query("select status from student_studij where student = $userid"))[0];
Ovdje bi trebalo koristiti db_get jer ti radiš cast array u int što je malo čudno.

2020-02-23 10:47 UTC, vljubovic commented on lib/config.php
> +<?php if (ini_get("short_open_tag") != 1) exit; ?><?
Ne bi trebalo da imaš lib/config.php na repozitoriju

2020-02-23 10:47 UTC, vljubovic commented on student/prijava_ispita.php
> +$s_s = (int)db_fetch_row(db_query("select status from student_studij where student = $userid"))[0];
Isto.

2020-02-23 10:47 UTC, vljubovic commented on studentska/osobe.php
> +            if($semestar == 5 or $semestar == 6 or $semestar == 9 or $semestar == 10){
Treba u uslov dodati i ciklus. Što se tiče 9 i 10 semestra, oni se u zamgeru ne vode kao semestar 9 i 10 nego kao semestar 3 i 4 ali je $ciklus == 2

2020-07-12 15:19 UTC, vljubovic commented
Moramo zatvoriti ovaj PR jer je ovo već urađeno :)

2020-07-12 15:19 UTC, closed without merging