Issue-29
etf-sarajevo/zamger pull request #41
Opened 2020-05-10 20:40 UTC by aladinkapic

Detalji u issue-29.md

2020-05-11 08:26 UTC, vljubovic requested changes

2020-05-11 08:26 UTC, vljubovic commented on nastavnik/dodavanje_asistenata.php
> +            $nastavnik = db_fetch1($nastavnik)[0] ? : 0; // Ukoliko nema pristup nastavnika - dodaj
Za ovaj use case imaš u APIju funkciju db_get:
$nastavnik = db_get("SELECT COUNT(osoba) FROM privilegije WHERE privilegija...");

2020-05-11 08:26 UTC, vljubovic commented on nastavnik/dodavanje_asistenata.php
> +                <option value="<?php echo $o[0]; ?>" <?php if(isset($osoba)){if($osoba == $o[0]) echo 'selected';} ?> >
Zašto ne if (isset($osoba) && $osoba == $o[0]) ?? U PHPu je ista kratkospojna evaluacija kao u C i C++ :)

2020-05-11 08:26 UTC, vljubovic commented on nastavnik/dodavanje_asistenata.php
> +            <td style="padding:4px 20px;"><font style="font-family:DejaVu Sans,Verdana,Arial,sans-serif;font-size:11px;font-weight:bold;color:white;">#</font></td>
Ja ne bih ovdje stavljao style, postoji jedinstveni CSS za čitav zamger i možemo njega eventualno dorađivati (ima za table  neki stil samo umjesto td bi trebao koristiti th).

2020-05-11 08:26 UTC, vljubovic commented on nastavnik/dodavanje_asistenata.php
> +            <option value="3" <?php if(isset($uloga)){if($uloga == 3) echo 'selected';} ?>>Superasistent</option>
Ovdje bi trebalo umjesto "uloga" pisati "Nivo pristupa" i postojati dvije opcije: asistent i superasistent.

2020-07-12 14:33 UTC, aladinkapic commented on nastavnik/dodavanje_asistenata.php
> +            $nastavnik = db_fetch1($nastavnik)[0] ? : 0; // Ukoliko nema pristup nastavnika - dodaj
Done !

2020-07-12 15:18 UTC, vljubovic approved these changes

2020-07-12 15:19 UTC, vljubovic commented
Moramo zatvoriti ovaj PR jer je ovo već urađeno :)

2020-07-12 15:19 UTC, closed without merging